import "./globals.scss";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { SearchProvider } from "./context/SearchContext";
import { CartProvider } from "./context/CartContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Exam Eatly-app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <CartProvider>
        <SearchProvider>
          <body className={inter.className}>
            <h1 className="visually-hidden">Eatly</h1>
            <div>{children}</div>
          </body>
        </SearchProvider>
      </CartProvider>
    </html>
  );
}
